name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify the Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build  # Ensure you have a "build" script in package.json that runs tsc

      - name: Run Test1
        run: |
          output=$(node dist/Test1.js)
          exit_code=$?
          
          echo "Output: $output"  # Display output for debugging

          if [ $exit_code -ne 0 ]; then
            echo "Error $exit_code"
            exit 1
          fi